-- Esquema base reconstruido desde el código actual del proyecto,
-- excluyendo la parte de devoluciones (`returns`) y las columnas
-- específicas de facturas rectificativas.

create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category_id bigint references public.categories(id) on delete set null,
  slug text not null unique,
  name text not null,
  description text,
  price_cents integer not null default 0 check (price_cents >= 0),
  compare_at_cents integer check (compare_at_cents is null or compare_at_cents >= 0),
  featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  name text not null default 'Principal',
  color_name text,
  color_hex text,
  size_label text,
  price_cents integer check (price_cents is null or price_cents >= 0),
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  position integer not null default 1 check (position >= 1),
  created_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  url text not null,
  alt_text text,
  position integer not null default 1 check (position >= 1),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid,
  created_at timestamptz not null default now(),
  shipping_method text not null default 'standard',
  payment_method text not null default 'stripe',
  shipping jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  subtotal_cents integer not null default 0 check (subtotal_cents >= 0),
  shipping_cents integer not null default 0 check (shipping_cents >= 0),
  total_cents integer not null default 0 check (total_cents >= 0),
  status text not null default 'pending',
  stripe_session_id text,
  stripe_payment_intent_id text
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null default 0 check (unit_price_cents >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id text primary key,
  order_id text not null references public.orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  total_cents integer not null default 0 check (total_cents >= 0),
  customer text not null default 'Cliente'
);

create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  status text not null default 'active' check (status in ('active', 'checked_out', 'abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  variant_id uuid references public.product_variants(id) on delete set null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null default 0 check (unit_price_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_is_active on public.products(is_active);
create index if not exists idx_products_featured on public.products(featured);
create index if not exists idx_product_variants_product_id on public.product_variants(product_id);
create index if not exists idx_product_variants_product_active on public.product_variants(product_id, is_active);
create index if not exists idx_product_images_product_id on public.product_images(product_id);
create index if not exists idx_product_images_product_position on public.product_images(product_id, position);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_cart_items_cart_id on public.cart_items(cart_id);
create index if not exists idx_cart_items_product_id on public.cart_items(product_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_carts_touch_updated_at on public.carts;
create trigger trg_carts_touch_updated_at
before update on public.carts
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_cart_items_touch_updated_at on public.cart_items;
create trigger trg_cart_items_touch_updated_at
before update on public.cart_items
for each row
execute function public.touch_updated_at();

create or replace function public.get_or_create_cart(p_cart_token uuid default null)
returns setof public.carts
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_cart public.carts%rowtype;
  new_cart public.carts%rowtype;
begin
  if p_cart_token is not null then
    select *
      into existing_cart
      from public.carts
     where token = p_cart_token
       and status = 'active'
     limit 1;

    if found then
      update public.carts
         set updated_at = now()
       where id = existing_cart.id
       returning * into existing_cart;

      return next existing_cart;
      return;
    end if;
  end if;

  insert into public.carts (status)
  values ('active')
  returning * into new_cart;

  return next new_cart;
end;
$$;

create or replace function public.get_cart_items(p_cart_token uuid)
returns table (
  item_id uuid,
  cart_id uuid,
  product_id uuid,
  variant_id uuid,
  quantity integer,
  unit_price_cents integer,
  product_slug text,
  product_name text,
  product_price_cents integer,
  image_url text,
  variant_name text,
  color_name text,
  color_hex text,
  size_label text,
  variant_stock integer
)
language sql
security definer
set search_path = public
as $$
  select
    ci.id as item_id,
    ci.cart_id,
    ci.product_id,
    ci.variant_id,
    ci.quantity,
    ci.unit_price_cents,
    p.slug as product_slug,
    p.name as product_name,
    p.price_cents as product_price_cents,
    pi.url as image_url,
    pv.name as variant_name,
    pv.color_name,
    pv.color_hex,
    pv.size_label,
    pv.stock as variant_stock
  from public.carts c
  join public.cart_items ci
    on ci.cart_id = c.id
  join public.products p
    on p.id = ci.product_id
  left join public.product_variants pv
    on pv.id = ci.variant_id
  left join lateral (
    select url
    from public.product_images
    where product_id = p.id
    order by position asc, id asc
    limit 1
  ) pi on true
  where c.token = p_cart_token
    and c.status = 'active'
  order by ci.created_at asc;
$$;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;
